### ISSUE TITLE
issue building python-setuptools

### ISSUE THREAD

**Issue by swinny89** [kisslinux/repo#76]
Not sure if this is the right place to bring up this issue. I am getting errors trying to build python-setuptools. I am in a kiss-chroot.

```
/ # kiss b python-setuptools
=> Resolving dependencies...
=> Building: python-setuptools.
=> Checking to see if any dependencies have already been built...
=> Installing any pre-built dependencies...
=> [python-setuptools]: Checking repository files...
=> [python-setuptools]: Downloading sources...
=> [python-setuptools]: Found cached source 'v41.1.0.tar.gz'.
=> [python-setuptools]: Extracting sources...
adding minimal entry_points
Regenerating egg_info
Traceback (most recent call last):
  File "setup.py", line 9, in <module>
    import setuptools
  File "/var/cache/kiss/build-11734/python-setuptools/setuptools/__init__.py", line 20, in <module>
    from setuptools.dist import Distribution, Feature
  File "/var/cache/kiss/build-11734/python-setuptools/setuptools/dist.py", line 35, in <module>
    from setuptools import windows_support
  File "/var/cache/kiss/build-11734/python-setuptools/setuptools/windows_support.py", line 2, in <module>
    import ctypes
  File "/usr/lib/python3.7/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ModuleNotFoundError: No module named '_ctypes'
Traceback (most recent call last):
  File "bootstrap.py", line 64, in <module>
    __name__ == '__main__' and main()
  File "bootstrap.py", line 61, in main
    run_egg_info()
  File "bootstrap.py", line 54, in run_egg_info
    subprocess.check_call(cmd)
  File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'setup.py', 'egg_info']' returned non-zero exit status 1.
!> [python-setuptools]: Build failed.
```

**Comment by dylanaraps** [comment]
Run `kiss update` and rebuild Python (which will build `3.6.8` instead of `3.7`). I just reverted its version back.

**Comment by swinny89** [comment]
@dylanaraps 
Thanks, that seems to have worked. I am now stuck on another package which fails to build. Should I open a new issue like this one for each issue I come in contact with? Not sure what standard procedure is for these kinds of things.

**Comment by dylanaraps** [comment]
A new issue would be preferable (easier to search for/find later). :+1:

Closing this. Open a new issue!

(I have a few hours of free time now if you're able to open a new issue)
